node('nodejs') {
  stage 'init'
    openshift.withCluster() { // Use "default" cluster or fallback to OpenShift cluster detection
      echo "Hello from the project running Jenkins: ${openshift.project()}"
      currproject = openshift.project()
    }
  stage 'build'
    openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')

  stage 'tag'
    openshiftTag(namespace: currproject, sourceStream: 'nodejs-ex', sourceTag: 'latest', destinationNamespace: currproject, destinationStream: 'nodejs-ex', destinationTag: 'noelotest')

  stage 'deploy'
    openshiftDeploy(deploymentConfig: 'nodejs-ex', namespace: currproject)

}
