node('nodejs') {
  echo "In project: ${openshift.project()}"
  stage 'build'
    openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')

  stage 'tag'
    openshiftTag(namespace: ${openshift.project(), sourceStream: 'nodejs-example', sourceTag: 'latest', destinationNamespace: ${openshift.project(), destinationStream: 'nodejs-example', destinationTag: 'latest')

  stage 'deploy'
    openshiftDeploy(deploymentConfig: 'nodejs-example', namespace: ${openshift.project())

}
