node('nodejs') {
  stage 'init'
    openshift.withCluster() { // Use "default" cluster or fallback to OpenShift cluster detection
      echo "Hello from the project running Jenkins: ${openshift.project()}"
    }
  stage 'build'
    openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
    currproject = openshift.project()

  stage 'tag'
    openshiftTag(namespace: ${currproject}, sourceStream: 'nodejs-example', sourceTag: 'latest', destinationNamespace: ${currproject}, destinationStream: 'nodejs-example', destinationTag: 'testready')

  stage 'deploy'
    openshiftDeploy(deploymentConfig: 'nodejs-example', namespace: ${currproject})

}
